/**
 * Contexto histórico dos corpos celestes de referência.
 *
 * Separado de bodyInfoContent para manter fatos estáticos e narrativa histórica
 * em responsabilidades distintas.
 */

import type { BodyId } from './bodyInfoContent';

export interface BodyHistory {
    historyPt: string;
    historyEn: string;
}

export const BODY_HISTORY: Record<BodyId, BodyHistory> = {
    sun: {
        historyPt: 'O Sol foi adorado como divindade em praticamente todas as culturas antigas — Ra no Egito, Hélio na Grécia, Inti nos Andes. Cada povo inventava uma história diferente para explicar a luz que aquecia o mundo, mas todos chegavam à mesma conclusão: ela era sagrada. Em 1543, Copérnico ousou propor que era o Sol, e não a Terra, o centro do sistema planetário — e o mundo tardou séculos para aceitar isso. A verdadeira natureza do Sol só foi compreendida no século XX: em 1920, Arthur Eddington sugeriu que a fusão de hidrogênio poderia ser sua fonte de energia. Era uma ideia radical para a época, confirmada décadas depois quando a física nuclear ganhou maturidade suficiente para dar sentido ao que estava acontecendo no interior de uma estrela.',
        historyEn: 'The Sun was worshipped as a deity in virtually every ancient culture — Ra in Egypt, Helios in Greece, Inti in the Andes. Each civilization invented different stories to explain the light that warmed their world, but all reached the same conclusion: it was sacred. In 1543, Copernicus dared to propose that the Sun, not Earth, was the center of the planetary system — and the world took centuries to fully accept it. The Sun\'s true nature was only understood in the 20th century: in 1920, Arthur Eddington suggested hydrogen fusion as its energy source. It was a radical idea for the time, confirmed decades later once nuclear physics had matured enough to make sense of what was happening inside a star.',
    },
    earth: {
        historyPt: 'Por milênios, a Terra foi considerada o centro imóvel do universo — e por que não seria? Ela não balança, não parece girar, e o céu inteiro se move ao seu redor. Foi Copérnico quem a deslocou desse trono em 1543, e Galileu quem pagou o preço por confirmar isso com o telescópio. O nome "Terra" vem do latim, assim como "Earth" em inglês e "Erde" em alemão vêm de raízes proto-germânicas — todos significando simplesmente "chão". A esfericidade da Terra, ao contrário do que se pensa, já era conhecida pelos gregos antigos: por volta de 240 a.C., Eratóstenes mediu sua circunferência usando sombras e um poço no Egito, chegando a um resultado de notável precisão.',
        historyEn: 'For millennia, Earth was considered the immovable center of the universe — and why wouldn\'t it be? It doesn\'t shake, doesn\'t seem to spin, and the entire sky revolves around it. It was Copernicus who displaced it from that throne in 1543, and Galileo who paid the price for confirming it with the telescope. The name "Earth" comes from Old English and Proto-Germanic roots, just as "Erde" in German does — all meaning simply "ground." Contrary to popular myth, the spherical shape of the Earth was already known to the ancient Greeks: around 240 BC, Eratosthenes measured its circumference using shadows and a well in Egypt, arriving at a remarkably accurate result.',
    },
    moon: {
        historyPt: 'A Lua é o único corpo celeste além da Terra pisado por seres humanos — e talvez por isso nunca deixe de impressionar. Galileu foi o primeiro a voltá-la ao telescópio, em 1609, e ficou desconcertado com o que viu: montanhas, vales, crateras. Aquilo destruía a ideia aristotélica de que os corpos celestes eram esferas perfeitas e imutáveis. Séculos depois, as missões Apollo (1969–1972) trouxeram de volta cerca de 380 kg de amostras lunares que ainda são estudadas hoje. O nome vem do latim "Luna", que deixou rastros inesperados na língua: dele vieram "lunático", "lúnula" e o próprio conceito de mês — o tempo que a Lua leva para completar um ciclo.',
        historyEn: 'The Moon is the only celestial body beyond Earth ever walked on by humans — and perhaps that\'s why it never stops being awe-inspiring. Galileo was the first to turn a telescope to it, in 1609, and was unsettled by what he saw: mountains, valleys, craters. It shattered the Aristotelian idea that celestial bodies were perfect, unchanging spheres. Centuries later, the Apollo missions (1969–1972) brought back around 380 kg of lunar samples that are still studied today. The name comes from Latin "Luna," which left unexpected traces in language: from it came "lunatic," "lunula," and the very concept of the month — the time it takes the Moon to complete one cycle.',
    },
    mercury: {
        historyPt: 'Mercúrio é conhecido desde a Antiguidade, mas por muito tempo foi tratado como dois astros distintos — uma estrela que aparecia de manhã e outra que surgia ao entardecer — antes que os gregos percebessem que ambas eram o mesmo planeta. Os romanos o batizaram em homenagem ao mensageiro dos deuses, pela velocidade com que ele cruza o céu. A primeira sonda a visitá-lo foi a Mariner 10, em 1974, que revelou uma superfície densamente craterizada. A MESSENGER entrou em órbita em 2011 e passou quatro anos mapeando Mercúrio por completo, incluindo regiões nunca antes fotografadas. Entre suas descobertas mais surpreendentes: gelo de água em crateras permanentemente na sombra, próximas ao polo.',
        historyEn: 'Mercury has been known since antiquity, but was long treated as two separate objects — a star that appeared in the morning and another that rose at dusk — before the Greeks realized both were the same planet. The Romans named it after the messenger of the gods, for the speed with which it crosses the sky. The first spacecraft to visit it was Mariner 10, in 1974, which revealed a heavily cratered surface. MESSENGER entered orbit in 2011 and spent four years mapping Mercury completely, including regions never before photographed. Among its most surprising discoveries: water ice in permanently shadowed craters near the pole.',
    },
    venus: {
        historyPt: 'Vênus é o objeto mais brilhante do céu noturno depois da Lua, e durante séculos foi chamado de "estrela d\'alva" — sem que se soubesse que era um planeta. Os babilônios o registravam há mais de três mil anos, e quase todas as culturas antigas lhe atribuíram alguma divindade feminina: a deusa do amor, da beleza, do amanhecer. O nome romano homenageia Vênus, deusa do amor. A União Soviética foi pioneira na sua exploração: a Venera 7 (1970) foi a primeira sonda a pousar com sucesso em outro planeta e transmitir dados da superfície. O que ela encontrou foi perturbador — temperatura próxima a 460 °C e uma pressão atmosférica noventa vezes maior que a da Terra, hostil a qualquer sonda que tentasse permanecer por mais de uma hora.',
        historyEn: 'Venus is the brightest object in the night sky after the Moon, and for centuries was called the "morning star" — without anyone knowing it was a planet. The Babylonians recorded it more than three thousand years ago, and nearly every ancient culture assigned it a feminine deity: the goddess of love, beauty, or dawn. Its Roman name honors Venus, goddess of love. The Soviet Union pioneered its exploration: Venera 7 (1970) was the first spacecraft to successfully land on another planet and transmit data from the surface. What it found was unsettling — temperatures near 460 °C and atmospheric pressure ninety times greater than Earth\'s, an environment hostile enough to silence any probe within the hour.',
    },
    mars: {
        historyPt: 'Marte fascina a humanidade há milênios — seu tom avermelhado o associou à guerra e ao sangue em quase todas as culturas antigas. Os romanos o batizaram de Marte, deus da guerra. Em 1877, o astrônomo Giovanni Schiaparelli descreveu o que chamou de "canali" na superfície marciana — uma palavra italiana que significa "canais" no sentido de sulcos naturais, mas que foi traduzida para o inglês como "canals", sugerindo estruturas artificiais. Isso bastou para décadas de especulação sobre civilizações marcianas. A Mariner 4 (1965) foi a primeira sonda a fotografar Marte de perto e devolveu imagens de uma superfície árida e craterizada. Desde então, a busca não cessou — apenas mudou de escala: hoje, rovers investigam traços de vida microbiana passada na rocha e no subsolo.',
        historyEn: 'Mars has fascinated humanity for millennia — its reddish hue associated it with war and blood in nearly every ancient culture. The Romans named it after Mars, god of war. In 1877, astronomer Giovanni Schiaparelli described what he called "canali" on the Martian surface — an Italian word meaning natural channels or grooves, but mistranslated into English as "canals," implying artificial structures. That was enough to fuel decades of speculation about Martian civilizations. Mariner 4 (1965) was the first spacecraft to photograph Mars up close and returned images of a barren, cratered surface. Since then, the search has not stopped — it has only changed in scale: today, rovers probe ancient rock and subsurface layers for traces of past microbial life.',
    },
    jupiter: {
        historyPt: 'Júpiter era conhecido pelos babilônios há mais de três mil anos, que já rastreavam seus movimentos com precisão suficiente para fazer previsões astronômicas. Os romanos o nomearam em homenagem ao rei dos deuses — e nenhum outro planeta parecia mais adequado para carregar esse nome. Em 1610, Galileu apontou o telescópio para Júpiter e descobriu quatro luas orbitando-o: Io, Europa, Ganimedes e Calisto. Foi a primeira vez que alguém observava corpos celestes em órbita de algo que não era a Terra — uma prova direta de que o modelo geocêntrico não poderia estar completamente certo. A Grande Mancha Vermelha, uma tempestade que persiste há séculos, chegou a ser maior do que a Terra inteira — e ainda hoje, embora menor, continua girando.',
        historyEn: 'Jupiter was known to the Babylonians more than three thousand years ago, who tracked its movements with enough precision to make astronomical predictions. The Romans named it after the king of the gods — and no other planet seemed more fitting to carry that name. In 1610, Galileo turned the telescope to Jupiter and discovered four moons orbiting it: Io, Europa, Ganymede, and Callisto. It was the first time anyone had observed celestial bodies in orbit around something other than Earth — direct proof that the geocentric model could not be entirely right. The Great Red Spot, a storm that has persisted for centuries, was once larger than the entire Earth — and today, though smaller, it keeps on spinning.',
    },
    saturn: {
        historyPt: 'Saturno foi o planeta mais distante conhecido pelos antigos — o limite visível do sistema solar por milênios. Sua lentidão no céu o associou, em várias culturas, à passagem inexorável do tempo: na mitologia romana, Saturno era o deus da colheita e das eras, aquele que preside os ciclos que nenhum ser escapa. Galileu foi o primeiro a observar seus anéis, em 1610, mas não conseguiu entender o que via e os descreveu como "orelhas" do planeta. Foi Christiaan Huygens quem, em 1655, interpretou corretamente que se tratava de um anel — e na mesma época descobriu Titã, sua maior lua. A sonda Cassini orbitou Saturno de 2004 a 2017, transmitindo imagens dos anéis com um detalhe que ainda espanta.',
        historyEn: 'Saturn was the most distant planet known to the ancients — the visible boundary of the solar system for millennia. Its slow drift across the sky associated it, in many cultures, with the inexorable passage of time: in Roman mythology, Saturn was the god of the harvest and of ages, the one who presides over cycles from which no being escapes. Galileo was the first to observe its rings, in 1610, but he could not understand what he saw and described them as the planet\'s "ears." It was Christiaan Huygens who, in 1655, correctly interpreted them as a ring — and around the same time discovered Titan, Saturn\'s largest moon. The Cassini probe orbited Saturn from 2004 to 2017, transmitting images of the rings in detail that still astonishes.',
    },
    uranus: {
        historyPt: 'Urano tem a honra de ser o primeiro planeta descoberto com telescópio. William Herschel o identificou em 1781, pensando inicialmente ser um cometa — levou um tempo até que os cálculos de sua órbita revelassem que era um planeta. O nome vem do deus grego do céu primordial, Urano, pai de Saturno e avô de Zeus. A única sonda a visitá-lo foi a Voyager 2, em 1986, que revelou um mundo inclinado de lado — seu eixo de rotação é tão oblíquo que Urano orbita o Sol quase como uma bola rolando. Uma de suas peculiaridades mais poéticas está nos nomes de suas luas: ao contrário de todos os outros planetas, cujos satélites levam nomes da mitologia greco-romana, as luas de Urano foram batizadas com nomes de personagens de Shakespeare e Alexander Pope.',
        historyEn: 'Uranus has the distinction of being the first planet discovered with a telescope. William Herschel identified it in 1781, initially thinking it was a comet — it took time before orbital calculations revealed it was a planet. The name comes from the Greek god of the primordial sky, Ouranos, father of Saturn and grandfather of Zeus. The only spacecraft to visit it was Voyager 2, in 1986, which revealed a world tilted on its side — its rotational axis is so oblique that Uranus orbits the Sun almost like a rolling ball. One of its most poetic peculiarities lies in the names of its moons: unlike every other planet, whose satellites carry names from Greco-Roman mythology, the moons of Uranus were named after characters from Shakespeare and Alexander Pope.',
    },
    neptune: {
        historyPt: 'Netuno foi o primeiro planeta descoberto pela matemática antes de ser visto pelo telescópio — uma façanha que ainda impressiona. Em 1846, perturbações na órbita de Urano levaram Urbain Le Verrier e John Couch Adams, trabalhando de forma independente, a calcular onde deveria haver um planeta desconhecido. Na mesma noite em que Le Verrier enviou suas coordenadas a Johann Galle, em Berlim, Galle apontou o telescópio e encontrou Netuno exatamente onde as equações disseram que ele estaria. Foi batizado em homenagem ao deus romano do mar por seu azul profundo. Sua maior lua, Tritão, orbita na direção contrária à rotação do planeta — um comportamento que sugere que ela não nasceu ali, mas foi capturada pelo campo gravitacional de Netuno em algum momento remoto da história do sistema solar.',
        historyEn: 'Neptune was the first planet discovered through mathematics before being seen through a telescope — a feat that still impresses. In 1846, perturbations in the orbit of Uranus led Urbain Le Verrier and John Couch Adams, working independently, to calculate where an unknown planet must lie. The very night Le Verrier sent his coordinates to Johann Galle in Berlin, Galle pointed the telescope and found Neptune exactly where the equations said it would be. It was named after the Roman god of the sea for its deep blue color. Its largest moon, Triton, orbits in the opposite direction to the planet\'s rotation — a behavior suggesting it was not born there, but was captured by Neptune\'s gravitational field at some remote point in the solar system\'s history.',
    },
};
